### ISSUE TITLE
install on vps

### ISSUE THREAD

**Issue by KvizadSaderah** [jaesivsm/JARR#219]
Hello sir!

Can you help me debug, again?

I'm trying to install JARR to VPS to my domain like `https://example.com`

And i'm using apache to route it, but can't achive result.

Can you help me what is wrong, and how to fix that?

cat prod.yml

```
version: '3'
services:
  jarr-server:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    ports:
      - "127.0.0.1:8500:8000"
    # You'll a folder with at least jarr.json, logging.ini and gunicorn.py
    volumes:
      - ../example_conf/:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      jarr:
  jarr-front:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/front
      args:
        PUBLIC_URL: http://example.com:8501/
        REACT_APP_API_URL: http://localhost:8500/
    ports:
      - "127.0.0.1:8501:80"
    depends_on:
      - jarr-server
    networks:
      - jarr
  jarr-worker:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    # You'll a folder with at least jarr.json, logging.ini and gunicorn.py
    volumes:
      - ../example_conf/:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - jarr
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq
    networks:
      - jarr
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - jarr
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - jarr
    # remove that on real prod env and set proper db password
    environment:
      - POSTGRES_PASSWORD=E5XrjanDTeUUiG3P4caPHBnddcgBxYoTdPJ4SMdq7awLn3BBzz 
      - POSTGRES_HOST_AUTH_METHOD=trust
    # Directory in which your db will save its data, change it to some absolute path
    volumes:
      - ../.jarr-data:/var/lib/postgresql/data

networks:
  jarr:
```

cat example.com.conf

```
<VirtualHost *:80>
    ServerName example.com
    ServerAlias www.example.com
    ErrorLog /var/log/apache2/example-error.log
    CustomLog /var/log/apache2/example-access.log combined

    # Redirect all HTTP traffic to HTTPS
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
```

upd: tried to run local on debian VM to (with default settings) to check if it works for me, or i'm doing something wrong from beginning, so it's works localy. 
But how to tide it to custom domain? that it would work? >_<
